BeaconAndLoaves/BeaconAndLoaves.csproj, BeaconAndLoaves/ClientApp/package.json, BeaconAndLoaves/Data/UserRepository.cs, BeaconAndLoaves/Models/CreateUserRequest.cs, BeaconAndLoaves/Models/User.cs, BeaconAndLoaves/Startup.cs, BeaconAndLoaves/Validators/CreaeteUserRequestValidator.cs, BeaconAndLoaves/appsettings.json
Hey guys. I went ahead and made some folders, made some changes to startup.cs and appsettings and added my code for my user model, user request and user request validator.
Wanna give it a peek and we can call this a starting point?
When I asked Nathan about the sprint he indicated that he hoped we'd be done with api stuff by Saturday end of class. I thought I'd jump on this part so that tomorrow night we can dig into coding.
Sound good?
=> User model

BeaconAndLoaves/Controllers/PropertiesController.cs, BeaconAndLoaves/Data/PropertyRepository.cs, BeaconAndLoaves/Models/Property.cs
- Getting All Properties with get request
- Getting Single Property with get Request and passing id
- Updating Property with put request and passing whole object.
- Deleting property with delete request updating isActive status
=> Rp get properties

BeaconAndLoaves/Controllers/UsersController.cs, BeaconAndLoaves/Data/UserRepository.cs
delete user is refactored and working. update user is added.
=> Sdw update user

BeaconAndLoaves/Controllers/RentalsController.cs, BeaconAndLoaves/Data/RentalRepository.cs, BeaconAndLoaves/Models/CreateRentalRequest.cs, BeaconAndLoaves/Models/Rental.cs, BeaconAndLoaves/Validators/CreateRentalRequestValidator.cs
These are the basic files for rentals.
=> Sw rental scaffolding

BeaconAndLoaves/Controllers/RentalsController.cs, BeaconAndLoaves/Data/RentalRepository.cs, BeaconAndLoaves/Startup.cs
creating rental contract is working.
=> create rental working

BeaconAndLoaves/Controllers/RentalsController.cs, BeaconAndLoaves/Data/RentalRepository.cs
=> Rp update rental

BeaconAndLoaves/Controllers/LikedPropertiesController.cs, BeaconAndLoaves/Data/LikedPropertyRepository.cs, BeaconAndLoaves/Models/CreateLikedPropertyRequest.cs, BeaconAndLoaves/Models/LikedProperty.cs, BeaconAndLoaves/Startup.cs, BeaconAndLoaves/Validators/CreateLikedPropertyRequestValidator.cs
=> Creating likedProperty

BeaconAndLoaves/Controllers/PropertiesController.cs, BeaconAndLoaves/Data/PropertyRepository.cs, BeaconAndLoaves/Models/CreatePropertyRequest.cs, BeaconAndLoaves/Models/Property.cs
- Added CreatedOn property on Property Model
- Added IsActive on Update for Property
=> Rp add created on

BeaconAndLoaves/ClientApp/src/App/App.js, BeaconAndLoaves/ClientApp/src/components/pages/Home/Home.js, BeaconAndLoaves/ClientApp/src/components/pages/Profile/Profile.js, BeaconAndLoaves/ClientApp/src/components/pages/Properties/Properties.js
- /home takes to home page which displays Profile and Properties icons
- Clicking on Profile takes to profile page
- Clicking on Properties to rent takes to properties page
=> Homepage is displaying and clicking on icon takes to the relative pages

BeaconAndLoaves/ClientApp/src/App/App.js, BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.scss, BeaconAndLoaves/ClientApp/src/components/pages/LikedProperties/LikedProperties.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclearDetail/SiloNuclearDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclearDetail/SiloNuclearDetail.scss, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclears/SiloNuclears.js, BeaconAndLoaves/ClientApp/src/helpers/data/propertiesRequests.js, BeaconAndLoaves/ClientApp/src/helpers/data/smashRequests.js
=> Rp property detail

BeaconAndLoaves/ClientApp/package-lock.json, BeaconAndLoaves/ClientApp/src/App/App.js, BeaconAndLoaves/ClientApp/src/components/pages/AddEditProperty/AddEditProperty.js, BeaconAndLoaves/ClientApp/src/components/pages/Home/Home.js, BeaconAndLoaves/ClientApp/src/components/pages/Home/Home.scss
- added Liked Properties and Add Property icon to home page
=> Rp modify profile page

BeaconAndLoaves/ClientApp/src/components/pages/AddEditProperty/AddEditProperty.js, BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/LightHouses/LightHouses.js, BeaconAndLoaves/ClientApp/src/helpers/data/propertiesRequests.js, BeaconAndLoaves/ClientApp/src/helpers/data/smashRequests.js, BeaconAndLoaves/Data/PropertyRepository.cs
=> Rp add property

BeaconAndLoaves/ClientApp/src/components/pages/Profile/Profile.js, BeaconAndLoaves/ClientApp/src/components/pages/Profile/Profile.scss, BeaconAndLoaves/ClientApp/src/components/pages/Register/Register.js, BeaconAndLoaves/ClientApp/src/components/pages/Register/Register.scss, BeaconAndLoaves/ClientApp/src/helpers/propz/userShape.js
fixed proptype error
did some more styling
edit profile is working
=> Sw edit profile

BeaconAndLoaves/ClientApp/src/components/pages/LightHouses/LightHouse.scss, BeaconAndLoaves/ClientApp/src/components/pages/LightHouses/LightHouses.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclears/SiloNuclears.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleLightHouse/SingleLightHouse.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleSiloNuclear/SingleSiloNuclear.js
- Ascend and descend properties...
=> Rp latest property

BeaconAndLoaves/ClientApp/src/components/pages/Register/Register.js, BeaconAndLoaves/ClientApp/src/components/pages/Register/Register.scss, BeaconAndLoaves/ClientApp/src/helpers/propz/userShape.js
added required fields to register
=> made register fields required

BeaconAndLoaves/ClientApp/package-lock.json, BeaconAndLoaves/ClientApp/package.json, BeaconAndLoaves/ClientApp/src/components/pages/LightHouses/LightHouses.js, BeaconAndLoaves/ClientApp/src/components/pages/LightHouses/LightHouses.scss, BeaconAndLoaves/ClientApp/src/components/pages/OwnerProperties/OwnerProperties.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclears/SiloNuclears.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclears/SiloNuclears.scss
- Given owners have properties to rent, When the user clicks on the search input field in the navigation bar and the user types the name, city or state of a property
=> Rp property search

BeaconAndLoaves/ClientApp/package-lock.json, BeaconAndLoaves/ClientApp/package.json, BeaconAndLoaves/ClientApp/src/App/App.js, BeaconAndLoaves/ClientApp/src/components/pages/EditProperty/EditProperty.js, BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.scss, BeaconAndLoaves/ClientApp/src/components/pages/LightHouses/LightHouses.js, BeaconAndLoaves/ClientApp/src/components/pages/Rental/Rental.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclearDetail/SiloNuclearDetail.js, BeaconAndLoaves/ClientApp/src/helpers/data/propertiesRequests.js, BeaconAndLoaves/Controllers/PropertiesController.cs, BeaconAndLoaves/Controllers/RentalsController.cs, BeaconAndLoaves/Data/PropertyRepository.cs, BeaconAndLoaves/Data/RentalRepository.cs
=> Rp edit property

BeaconAndLoaves/ClientApp/package-lock.json, BeaconAndLoaves/ClientApp/package.json, BeaconAndLoaves/ClientApp/src/components/pages/Rental/Rental.js, BeaconAndLoaves/ClientApp/src/components/pages/Rental/Rental.scss, BeaconAndLoaves/ClientApp/src/helpers/data/rentalRequests.js, BeaconAndLoaves/Controllers/RentalsController.cs, BeaconAndLoaves/Data/RentalRepository.cs
This should show dates blocked out for any dates the property is already rented AND should block out all dates before 'today.'
=> Sw exclude dates

BeaconAndLoaves/ClientApp/src/components/pages/ConfirmationModal/ConfrimationModal.js, BeaconAndLoaves/ClientApp/src/components/pages/LikedProperties/LikedProperties.js, BeaconAndLoaves/ClientApp/src/components/pages/Profile/Profile.js, BeaconAndLoaves/ClientApp/src/components/pages/Rental/Rental.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleLikedProperty/SingleLikedProperty.js
When renting a property, a modal should now appear to confirm your information. You can either complete the rental from there or go back and make changes.
=> Sw rental confirmation

BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/LikeButton/LikeButton.js, BeaconAndLoaves/ClientApp/src/components/pages/LikeButton/LikeButton.scss, BeaconAndLoaves/ClientApp/src/components/pages/LikedProperties/LikedProperties.js, BeaconAndLoaves/ClientApp/src/components/pages/OwnerProperties/OwnerProperties.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclearDetail/SiloNuclearDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleLikedProperty/SingleLikedProperty.js
- Wrote Likebutton component to reuse on other component.
- On liked Properties section, properties are displaying with red heart and clicking on the icon will remove the property from liked properties.
=> Rp refactor

BeaconAndLoaves/ClientApp/package-lock.json, BeaconAndLoaves/ClientApp/package.json, BeaconAndLoaves/ClientApp/src/components/pages/LikedProperties/LikedProperties.js, BeaconAndLoaves/ClientApp/src/components/pages/Rental/Rental.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleLikedProperty/SingleLikedProperty.js
Clicking 'rent me' on a liked property should open the rental modal.
=> liked property rent button bringing up model and sending id

BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/LikeButton/LikeButton.js, BeaconAndLoaves/ClientApp/src/components/pages/LikeButton/LikeButton.scss, BeaconAndLoaves/ClientApp/src/components/pages/LikedProperties/LikedProperties.js, BeaconAndLoaves/ClientApp/src/components/pages/OwnerProperties/OwnerProperties.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclearDetail/SiloNuclearDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleLikedProperty/SingleLikedProperty.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleOwnerProperty/SingleOwnerProperty.js, BeaconAndLoaves/ClientApp/src/helpers/data/smashRequests.js
- Allows to click on like and unlike from owner's list of properties.
=> Rp like button on owner properties

BeaconAndLoaves/ClientApp/src/components/pages/Profile/Profile.js, BeaconAndLoaves/ClientApp/src/helpers/data/propertiesRequests.js, BeaconAndLoaves/Data/UserRepository.cs
- If Owner of the property decide to delete the account it will delete associated properties to the owner
=> Rp acct deletion property delete

BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclearDetail/SiloNuclearDetail.js
- Deletes the property upon clicking delete button
=> Rp delete property

BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/LikeButton/LikeButton.js, BeaconAndLoaves/ClientApp/src/components/pages/LikedProperties/LikedProperties.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclearDetail/SiloNuclearDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleLikedProperty/SingleLikedProperty.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleOwnerProperty/SingleOwnerProperty.js, BeaconAndLoaves/ClientApp/src/helpers/data/likedPropertyRequests.js, BeaconAndLoaves/Controllers/LikedPropertiesController.cs, BeaconAndLoaves/Data/LikedPropertyRepository.cs
- Fix the bug....Now you can click as often as you like on heart button  and from liked properties it is updating the state as you unlike the property
=> Rp like button bug fix

BeaconAndLoaves/ClientApp/src/App/App.js, BeaconAndLoaves/ClientApp/src/components/pages/PaymentMethodForm/PaymentMethodForm.js, BeaconAndLoaves/ClientApp/src/components/pages/Profile/Profile.js, BeaconAndLoaves/ClientApp/src/components/pages/Register/Register.js, BeaconAndLoaves/ClientApp/src/components/pages/SinglePaymentMethodModal/SinglePaymentMethodModal.js
Alrighty, had to do some refactoring to get this happening but, when registering a new user after hitting enter, you should be taken to the add account modal.
=> Sw require payment account

BeaconAndLoaves/ClientApp/src/App/App.js, BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/LikedProperties/LikedProperties.js, BeaconAndLoaves/ClientApp/src/components/pages/OwnerProperties/OwnerProperties.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclearDetail/SiloNuclearDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleOwnerProperty/SingleOwnerProperty.js
- displaying appropriate userID and showing only user associated properties
=> Rp another bug with liked properties

BeaconAndLoaves/ClientApp/package-lock.json, BeaconAndLoaves/ClientApp/package.json, BeaconAndLoaves/ClientApp/src/components/pages/PaymentMethodForm/PaymentMethodForm.js, BeaconAndLoaves/ClientApp/src/components/pages/SinglePaymentMethodModal/SinglePaymentMethodModal.js
gets account type to show up on get single payment method, also adds input validation to the form, and @shanedwilson added in a way to get the date to show up in MM/YYYY on the edit screen (of a payment method)
=> Sw payment method date

BeaconAndLoaves/ClientApp/src/App/App.js, BeaconAndLoaves/ClientApp/src/components/SingleRentalItem/SingleRentalItem.js, BeaconAndLoaves/ClientApp/src/components/pages/Profile/Profile.js, BeaconAndLoaves/ClientApp/src/components/pages/RentingHistory/RentingHistory.js, BeaconAndLoaves/ClientApp/src/components/pages/RentingHistory/RentingHistory.scss, BeaconAndLoaves/ClientApp/src/helpers/data/rentalRequests.js, BeaconAndLoaves/Controllers/RentalsController.cs, BeaconAndLoaves/Data/RentalRepository.cs
From Profile Page renter's history is displaying. Separated into future and past rentals.
=> Sw renting history

BeaconAndLoaves/ClientApp/src/App/App.js, BeaconAndLoaves/ClientApp/src/components/pages/EditProperty/EditProperty.js, BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/LightHouses/LightHouses.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclearDetail/SiloNuclearDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclears/SiloNuclears.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleOwnerProperty/SingleOwnerProperty.js, BeaconAndLoaves/ClientApp/src/helpers/data/smashRequests.js, BeaconAndLoaves/Data/PropertyRepository.cs, BeaconAndLoaves/Data/UserRepository.cs, BeaconAndLoaves/Models/Property.cs
- As Owner, availability of activating and deactivating property.
=> Rp deactivate property

BeaconAndLoaves/ClientApp/src/components/SingleRentalItem/SingleRentalItem.js, BeaconAndLoaves/ClientApp/src/components/pages/PaymentMethodForm/PaymentMethodForm.js, BeaconAndLoaves/ClientApp/src/components/pages/RentingHistory/RentingHistory.js, BeaconAndLoaves/ClientApp/src/components/pages/RentingHistory/RentingHistory.scss, BeaconAndLoaves/ClientApp/src/components/pages/RentingHistoryModal/RentingHistoryModal.js, BeaconAndLoaves/ClientApp/src/components/pages/SinglePaymentMethodModal/SinglePaymentMethodModal.js, BeaconAndLoaves/ClientApp/src/helpers/data/rentalRequests.js, BeaconAndLoaves/ClientApp/src/helpers/formatDate.js, BeaconAndLoaves/Data/RentalRepository.cs
Styled the renting history as tables
=> Sw style renting history

BeaconAndLoaves/ClientApp/src/components/SingleRentalItem/SingleRentalItem.js, BeaconAndLoaves/ClientApp/src/components/pages/PaymentMethodForm/PaymentMethodForm.js, BeaconAndLoaves/ClientApp/src/components/pages/RentingHistory/RentingHistory.js, BeaconAndLoaves/ClientApp/src/components/pages/RentingHistoryModal/RentingHistoryModal.js, BeaconAndLoaves/ClientApp/src/components/pages/SinglePaymentMethodModal/SinglePaymentMethodModal.js, BeaconAndLoaves/ClientApp/src/helpers/data/rentalRequests.js, BeaconAndLoaves/ClientApp/src/helpers/formatDate.js, BeaconAndLoaves/Data/RentalRepository.cs
Clicking on a rental in your history brings up a detail modal
=> Sw renting history detail

BeaconAndLoaves/ClientApp/src/App/App.js, BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.scss, BeaconAndLoaves/ClientApp/src/components/pages/OwnerRentals/OwnerRentals.js, BeaconAndLoaves/ClientApp/src/components/pages/OwnerRentals/OwnerRentals.scss, BeaconAndLoaves/ClientApp/src/components/pages/Profile/Profile.js, BeaconAndLoaves/ClientApp/src/components/pages/Profile/Profile.scss, BeaconAndLoaves/ClientApp/src/components/pages/RentingHistory/RentingHistory.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleOwnerRentalItem/SingleOwnerRentalItem.js, BeaconAndLoaves/ClientApp/src/helpers/data/rentalRequests.js, BeaconAndLoaves/Controllers/RentalsController.cs, BeaconAndLoaves/Data/RentalRepository.cs
- Owners are able to see future and past rentals
=> Rp rentals history

BeaconAndLoaves/ClientApp/public/index.html, BeaconAndLoaves/ClientApp/src/components/LikeButton/LikeButton.js, BeaconAndLoaves/ClientApp/src/components/pages/Home/Home.js, BeaconAndLoaves/ClientApp/src/components/pages/Home/Home.scss, BeaconAndLoaves/ClientApp/src/components/pages/LikedProperties/LikedProperties.js, BeaconAndLoaves/ClientApp/src/components/pages/OwnerDashboard/OwnerDashboard.js, BeaconAndLoaves/ClientApp/src/components/pages/OwnerDashboard/OwnerDashboard.scss, BeaconAndLoaves/ClientApp/src/components/pages/Profile/Profile.scss, BeaconAndLoaves/ClientApp/src/styles/_variables.scss
- styled homepage- added fonts, color palate, box shadow and animation
- added numbers of rentals to dashboard and styled according to profile
=> Rp owner dashboard72

BeaconAndLoaves/ClientApp/public/index.html, BeaconAndLoaves/ClientApp/src/components/LikeButton/LikeButton.js, BeaconAndLoaves/ClientApp/src/components/LikeButton/LikeButton.scss, BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/LightHouseDetail/LightHouseDetail.scss, BeaconAndLoaves/ClientApp/src/components/pages/LightHouses/LightHouses.js, BeaconAndLoaves/ClientApp/src/components/pages/LightHouses/LightHouses.scss, BeaconAndLoaves/ClientApp/src/components/pages/LikedProperties/LikedProperties.js, BeaconAndLoaves/ClientApp/src/components/pages/OwnerDashboard/OwnerDashboard.js, BeaconAndLoaves/ClientApp/src/components/pages/OwnerDashboard/OwnerDashboard.scss, BeaconAndLoaves/ClientApp/src/components/pages/OwnerProperties/OwnerProperties.js, BeaconAndLoaves/ClientApp/src/components/pages/Profile/Profile.js, BeaconAndLoaves/ClientApp/src/components/pages/Profile/Profile.scss, BeaconAndLoaves/ClientApp/src/components/pages/Properties/Properties.js, BeaconAndLoaves/ClientApp/src/components/pages/Properties/Properties.scss, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclearDetail/SiloNuclearDetail.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclearDetail/SiloNuclearDetail.scss, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclears/SiloNuclears.js, BeaconAndLoaves/ClientApp/src/components/pages/SiloNuclears/SiloNuclears.scss, BeaconAndLoaves/ClientApp/src/components/pages/SingleLightHouse/SingleLightHouse.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleLightHouse/SingleLightHouse.scss, BeaconAndLoaves/ClientApp/src/components/pages/SingleLikedProperty/SingleLikedProperty.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleLikedProperty/SingleLikedProperty.scss, BeaconAndLoaves/ClientApp/src/components/pages/SingleOwnerProperty/SingleOwnerProperty.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleOwnerProperty/SingleOwnerProperty.scss, BeaconAndLoaves/ClientApp/src/components/pages/SingleSiloNuclear/SingleSiloNuclear.js, BeaconAndLoaves/ClientApp/src/components/pages/SingleSiloNuclear/SingleSiloNuclear.scss, BeaconAndLoaves/ClientApp/src/styles/_variables.scss
- styling to properties page
- styling to lighthouses and silonuclears.
- styling to details page, liked properties page and owner properties page
- animation to owner dashboard.
=> Rp style properties

BeaconAndLoaves/ClientApp/src/components/RentingHistoryModal/RentingHistoryModal.js, BeaconAndLoaves/ClientApp/src/components/RentingHistoryModal/RentingHistoryModal.scss, BeaconAndLoaves/ClientApp/src/components/pages/RentingHistory/RentingHistory.js, BeaconAndLoaves/Data/RentalRepository.cs
styled modals associated with 'view my trips'
=> Sw trip page styling

BeaconAndLoaves/ClientApp/src/components/PaymentMethodForm/PaymentMethodForm.js, BeaconAndLoaves/ClientApp/src/components/PaymentMethodForm/PaymentMethodForm.scss, BeaconAndLoaves/ClientApp/src/components/RentalHistoryModal/RentalHistoryModal.js, BeaconAndLoaves/ClientApp/src/components/RentalHistoryModal/RentalHistoryModal.scss, BeaconAndLoaves/ClientApp/src/components/pages/OwnerRentals/OwnerRentals.js, BeaconAndLoaves/ClientApp/src/components/pages/Profile/Profile.js, BeaconAndLoaves/ClientApp/src/components/pages/Profile/Profile.scss, BeaconAndLoaves/ClientApp/src/components/pages/Register/Register.js, BeaconAndLoaves/ClientApp/src/components/pages/Register/Register.scss
Minor styling to registration page.
=> Sw registration styling

BeaconAndLoaves/ClientApp/src/components/PaymentMethodForm/PaymentMethodForm.js, BeaconAndLoaves/ClientApp/src/components/PaymentMethodForm/PaymentMethodForm.scss, BeaconAndLoaves/ClientApp/src/components/RentalHistoryModal/RentalHistoryModal.js, BeaconAndLoaves/ClientApp/src/components/RentalHistoryModal/RentalHistoryModal.scss, BeaconAndLoaves/ClientApp/src/components/pages/OwnerRentals/OwnerRentals.js
Styled the payment method modal and the Rental History Modal.
=> fixed payment method modal styling
